data = {
  Size: [
    { key: "768x1024", tag: "normal" },
    { key: "1024x768", tag: "normal" },
    { key: "640x960", tag: "normal" },
    { key: "960x640", tag: "normal" },
    { key: "576x1024", tag: "normal" },
    { key: "1024x576", tag: "normal" },
    { key: "640x1024", tag: "normal" },
    { key: "1024x640", tag: "normal" },
    { key: "768x768", tag: "normal" },
  ],
  Style: [
    { key: "Photo", tag: "normal" },
    { key: "Made", tag: "normal" },
    { key: "Cinematic", tag: "normal" },
    { key: "Digital Art", tag: "normal" },
    { key: "Dark Fantasy", tag: "normal" },
    { key: "Realistic Art", tag: "normal" },
    { key: "Cyberpunk", tag: "normal" },
    { key: "Fantasy", tag: "normal" },
    { key: "Sci-Fi", tag: "normal" },
    { key: "Post-Apocalyptic", tag: "normal" },
    { key: "Vintage", tag: "normal" },
    { key: "Anime", tag: "normal" },
    { key: "Hentai", tag: "porn" },
    { key: "Movie", tag: "normal" },
    { key: "3D", tag: "normal" },
    { key: "Comic", tag: "normal" },
    { key: "Cartoon", tag: "normal" },
    { key: "Steampunk", tag: "normal" },
    { key: "Watercolor", tag: "normal" },
    { key: "Oil", tag: "normal" },
    { key: "Gothic", tag: "normal" },
    { key: "Baroque", tag: "normal" },
    { key: "Surrealism", tag: "normal" },
    { key: "Art Deco", tag: "normal" },
    { key: "Kitsch", tag: "normal" },
    { key: "Psychedelic", tag: "normal" },
    { key: "Acrylic", tag: "normal" },
  ],
  Base: [
    { key: "woman", tag: "normal" },
    { key: "lesbian", tag: "normal" },
    { key: "shemale", tag: "porn" },
    { key: "ladyboy", tag: "porn" },
    { key: "gay", tag: "porn" },
  ],
  Tags: [
    { key: "perfect boobs", tag: "porn" },
    { key: "huge boobs", tag: "porn" },
    { key: "big tits", tag: "porn" },
    { key: "small tits", tag: "porn" },
    { key: "saggy tits", tag: "porn" },
    { key: "gigantic boobs", tag: "porn" },
    { key: "natural tits", tag: "porn" },
    { key: "nipples", tag: "porn" },
    { key: "tattoos", tag: "normal" },
    { key: "piercing", tag: "normal" },
    { key: "lipstick", tag: "normal" },
    { key: "long fingernails", tag: "normal" },
    { key: "selfie", tag: "normal" },
    { key: "mirror selfie", tag: "normal" },
    { key: "big ass", tag: "porn" },
    { key: "small ass", tag: "porn" },
    { key: "big cock", tag: "porn" },
    { key: "uncircumcised cock", tag: "porn" },
    { key: "big balls", tag: "porn" },
    { key: "veiny dick", tag: "porn" },
    { key: "perfect body", tag: "sexy" },
    { key: "babe", tag: "sexy" },
    { key: "busty", tag: "sexy" },
    { key: "skinny", tag: "normal" },
    { key: "thick", tag: "normal" },
    { key: "chubby", tag: "normal" },
    //{ key: "fat", tag: "normal" },
    //{ key: "bbw", tag: "porn" },
    //{ key: "ssbbw", tag: "porn" },
    { key: "muscular", tag: "normal" },
    { key: "pregnant", tag: "normal" },
    { key: "big hips", tag: "porn" },
    { key: "long legs", tag: "sexy" },
    { key: "feet", tag: "fetish" },
    { key: "thick thighs", tag: "sexy" },
    { key: "thighs", tag: "sexy" },
    { key: "barefoot", tag: "fetish" },
    { key: "collarbone", tag: "normal" },
    { key: "bare shoulders", tag: "sexy" },
    { key: "short", tag: "normal" },
    { key: "tall", tag: "normal" },
    { key: "hairy", tag: "normal" },
    { key: "shaved", tag: "porn" },
    { key: "pussy juice", tag: "porn" },
    { key: "short hair", tag: "normal" },
    { key: "long hair", tag: "normal" },
    { key: "mid-length hair", tag: "normal" },
    { key: "shiny skin", tag: "sexy" },
    { key: "tanned skin", tag: "sexy" },
    { key: "fairer skin", tag: "normal" },
    { key: "oiled body", tag: "sexy" },
    { key: "wet body", tag: "sexy" },
    { key: "body soap", tag: "normal" },
    { key: "tan lines", tag: "sexy" },
    { key: "armpits", tag: "fetish" },
    { key: "saliva", tag: "fetish" },
    { key: "sweat", tag: "normal" },
    { key: "athlete", tag: "normal" },
    { key: "flexible", tag: "normal" },
    { key: "bodybuilder", tag: "normal" },
    { key: "bimbo", tag: "fetish" },
    { key: "slutty", tag: "porn" },
    { key: "amateur", tag: "porn" },
    { key: "gyaru", tag: "fetish" },
    { key: "futanari", tag: "porn" },
    { key: "pawg", tag: "fetish" },
    { key: "arched eyebrow", tag: "normal" },
    { key: "real eyebrow", tag: "normal" },
    { key: "rounded eyebrow", tag: "normal" },
    { key: "straight eyebrow", tag: "normal" },
    { key: "back view", tag: "normal" },
    { key: "bent over", tag: "porn" },
    { key: "looking at viewer", tag: "normal" },
    { key: "looking back", tag: "normal" },
    { key: "from behind", tag: "normal" },
    { key: "profile shot", tag: "normal" },
    { key: "sideview", tag: "normal" },
  ],
  Action: [
    { key: "cumshot", tag: "porn" },
    { key: "pussy fucking", tag: "porn" },
    { key: "ass fucking", tag: "porn" },
    { key: "anal", tag: "porn" },
    { key: "blowjob", tag: "porn" },
    { key: "69", tag: "porn" },
    { key: "ahegao", tag: "fetish" },
    { key: "air kiss", tag: "sexy" },
    { key: "anal gape", tag: "fetish" },
    { key: "ass licking", tag: "porn" },
    { key: "ball licking", tag: "porn" },
    { key: "tits licking", tag: "porn" },
    { key: "bathing", tag: "normal" },
    { key: "begging", tag: "fetish" },
    { key: "bondage", tag: "fetish" },
    { key: "bukkake", tag: "porn" },
    //{ key: "cleaning dishes", tag: "normal" },
    //{ key: "cleaning floor", tag: "normal" },
    //{ key: "cooking", tag: "normal" },
    { key: "cowgirl fucking", tag: "porn" },
    { key: "crawling", tag: "fetish" },
    { key: "creampie", tag: "porn" },
    { key: "cuckold", tag: "fetish" },
    { key: "cum in mouth", tag: "porn" },
    { key: "cum in pussy", tag: "porn" },
    { key: "cum on ass", tag: "porn" },
    { key: "cum on feet", tag: "porn" },
    { key: "cum on thigh", tag: "porn" },
    { key: "cum on tits", tag: "porn" },
    { key: "cum swapping", tag: "fetish" },
    //{ key: "dancing", tag: "normal" },
    { key: "deepthroat", tag: "porn" },
    { key: "doggystyle", tag: "porn" },
    { key: "double penetration", tag: "porn" },
    { key: "facesitting", tag: "porn" },
    { key: "facial", tag: "porn" },
    { key: "femdom", tag: "fetish" },
    { key: "fingering", tag: "porn" },
    { key: "fisting", tag: "porn" },
    { key: "foot fetish", tag: "fetish" },
    { key: "footjob", tag: "porn" },
    { key: "flashing", tag: "fetish" },
    { key: "flashing panties", tag: "fetish" },
    { key: "flashing tits", tag: "fetish" },
    { key: "gangbang", tag: "porn" },
    { key: "gloryhole", tag: "porn" },
    { key: "gyno", tag: "normal" },
    { key: "handjob", tag: "porn" },
    { key: "humping", tag: "porn" },
    { key: "interracial", tag: "normal" },
    { key: "kissing", tag: "sexy" },
    { key: "kneeling", tag: "porn" },
    { key: "lift dress", tag: "porn" },
    { key: "lying", tag: "normal" },
    { key: "massage", tag: "normal" },
    { key: "masturbation", tag: "porn" },
    //{ key: "meditation", tag: "normal" },
    { key: "missionary", tag: "porn" },
    { key: "orgy", tag: "porn" },
    { key: "open mouth", tag: "porn" },
    { key: "pussy licking", tag: "porn" },
    //{ key: "roller skating", tag: "normal" },
    //{ key: "roleplay", tag: "porn" },
    //{ key: "running", tag: "normal" },
    { key: "seduction", tag: "sexy" },
    { key: "sleeping", tag: "normal" },
    //{ key: "sitting", tag: "normal" },
    { key: "smoking", tag: "normal" },
    { key: "spanking", tag: "porn" },
    { key: "splits", tag: "normal" },
    //{ key: "standing", tag: "normal" },
    { key: "spreading ass", tag: "fetish" },
    { key: "spreading pussy lips", tag: "porn" },
    { key: "spreading legs", tag: "porn" },
    //{ key: "squatting", tag: "normal" },
    //{ key: "skateboard", tag: "normal" },
    //{ key: "skis", tag: "normal" },
    //{ key: "snowboard", tag: "normal" },
    //{ key: "sun tanning", tag: "normal" },
    //{ key: "surfing", tag: "normal" },
    { key: "threesome", tag: "porn" },
    { key: "titjob", tag: "porn" },
    { key: "tribbing", tag: "porn" },
    { key: "undressing", tag: "porn" },
    { key: "upskirt", tag: "porn" },
    { key: "voyeur", tag: "fetish" },
    { key: "washing car", tag: "normal" },
    //{ key: "working out", tag: "normal" },
    //{ key: "yoga", tag: "normal" },
  ],
  View: [
    { key: "portrait", tag: "normal" },
    { key: "pov", tag: "normal" },
    { key: "full shot", tag: "normal" },
    { key: "medium shot", tag: "normal" },
    { key: "close up", tag: "normal" },
    { key: "fisheye", tag: "normal" },
    { key: "back view", tag: "normal" },
    { key: "bent over", tag: "porn" },
    { key: "looking at viewer", tag: "normal" },
    { key: "looking back", tag: "normal" },
    { key: "from behind", tag: "normal" },
    { key: "profile shot", tag: "normal" },
    { key: "sideview", tag: "normal" },
  ],
  Age: [
    { key: "age 18", tag: "normal" },
    { key: "age 20", tag: "normal" },
    { key: "age 30", tag: "normal" },
    { key: "age 40", tag: "normal" },
  ],
  Face: [
    { key: "happy", tag: "normal" },
    { key: "laughing", tag: "normal" },
    { key: "angry", tag: "normal" },
    { key: "ashamed", tag: "normal" },
    { key: "astonished", tag: "normal" },
    { key: "amazed", tag: "normal" },
    { key: "confused", tag: "normal" },
    { key: "creepy", tag: "normal" },
    { key: "exhausted", tag: "normal" },
    { key: "feared", tag: "normal" },
    { key: "indifferent look", tag: "normal" },
    { key: "impressed", tag: "normal" },
    { key: "orgasm", tag: "porn" },
    { key: "playful", tag: "normal" },
    { key: "pouting lips", tag: "sexy" },
    { key: "sad", tag: "normal" },
    { key: "screaming", tag: "normal" },
    { key: "smile", tag: "normal" },
    { key: "seductive", tag: "sexy" },
    { key: "serious", tag: "normal" },
    { key: "shocked", tag: "normal" },
    { key: "surprised", tag: "normal" },
  ],
  Colors: [
    { key: "black", tag: "normal" },
    { key: "white", tag: "normal" },
    { key: "gray", tag: "normal" },
    { key: "aqua", tag: "normal" },
    { key: "blue", tag: "normal" },
    { key: "brown", tag: "normal" },
    { key: "cyan", tag: "normal" },
    { key: "fuchsia", tag: "normal" },
    { key: "green", tag: "normal" },
    { key: "lime", tag: "normal" },
    { key: "magenta", tag: "normal" },
    { key: "maroon", tag: "normal" },
    { key: "navy", tag: "normal" },
    { key: "olive", tag: "normal" },
    { key: "orange", tag: "normal" },
    { key: "pink", tag: "normal" },
    { key: "purple", tag: "normal" },
    { key: "red", tag: "normal" },
    { key: "sapphire", tag: "normal" },
    { key: "silver", tag: "normal" },
    { key: "teal", tag: "normal" },
    { key: "yellow", tag: "normal" },
    { key: "dark", tag: "normal" },
    { key: "light", tag: "normal" },
    { key: "pastel", tag: "normal" },
    { key: "vivid", tag: "normal" },
    { key: "neon", tag: "normal" },
    { key: "glow", tag: "normal" },
    { key: "glitter", tag: "normal" },
  ],
  "Hair Color": [
    { key: "blonde", tag: "normal" },
    { key: "brunette", tag: "normal" },
    { key: "ginger", tag: "normal" },
    { key: "white hair", tag: "normal" },
    { key: "black hair", tag: "normal" },
    { key: "blue hair", tag: "normal" },
    { key: "green hair", tag: "normal" },
    { key: "purple hair", tag: "normal" },
    { key: "pink hair", tag: "normal" },
    { key: "multicolored hair", tag: "normal" },
  ],
  "Hair Style": [
    { key: "after sex hair", tag: "porn" },
    { key: "bangs hair", tag: "normal" },
    { key: "bobcut", tag: "normal" },
    { key: "box braids", tag: "normal" },
    { key: "braided hair", tag: "normal" },
    { key: "crimped hair", tag: "normal" },
    { key: "curly hair", tag: "normal" },
    { key: "french braid", tag: "normal" },
    { key: "frizzy hair", tag: "normal" },
    { key: "hair bun", tag: "normal" },
    { key: "high ponytail", tag: "normal" },
    { key: "inverted bobcut", tag: "normal" },
    { key: "messy hair", tag: "normal" },
    { key: "mohawk", tag: "normal" },
    { key: "pigtails", tag: "normal" },
    { key: "pixie hair", tag: "normal" },
    { key: "ponytail", tag: "normal" },
    { key: "slicked hair", tag: "normal" },
    { key: "straight hair", tag: "normal" },
    { key: "top knot hair", tag: "normal" },
    { key: "wild afro", tag: "normal" },
  ],
  Ethnicity: [
    { key: "african", tag: "normal" },
    { key: "african american", tag: "normal" },
    { key: "albanian", tag: "normal" },
    { key: "algerian", tag: "normal" },
    { key: "angolan", tag: "normal" },
    { key: "arabic", tag: "normal" },
    { key: "argentinian", tag: "normal" },
    { key: "armenian", tag: "normal" },
    { key: "asian", tag: "normal" },
    { key: "australian", tag: "normal" },
    { key: "austrian", tag: "normal" },
    { key: "belarusian", tag: "normal" },
    { key: "belgian", tag: "normal" },
    { key: "berber", tag: "normal" },
    { key: "bolivian", tag: "normal" },
    { key: "brazilian", tag: "normal" },
    { key: "british", tag: "normal" },
    { key: "bulgarian", tag: "normal" },
    { key: "burmese", tag: "normal" },
    { key: "cambodian", tag: "normal" },
    { key: "canadian", tag: "normal" },
    { key: "caucasian", tag: "normal" },
    { key: "chilean", tag: "normal" },
    { key: "chinese", tag: "normal" },
    { key: "colombian", tag: "normal" },
    { key: "croatian", tag: "normal" },
    { key: "cuban", tag: "normal" },
    { key: "czech", tag: "normal" },
    { key: "danish", tag: "normal" },
    { key: "dominican", tag: "normal" },
    { key: "ecuadorian", tag: "normal" },
    { key: "egyptian", tag: "normal" },
    { key: "eskimo", tag: "normal" },
    { key: "ethiopian", tag: "normal" },
    { key: "filipino", tag: "normal" },
    { key: "finnish", tag: "normal" },
    { key: "french", tag: "normal" },
    { key: "german", tag: "normal" },
    { key: "ghanaian", tag: "normal" },
    { key: "greek", tag: "normal" },
    { key: "guatemalan", tag: "normal" },
    { key: "haitian", tag: "normal" },
    { key: "himba", tag: "normal" },
    { key: "hungarian", tag: "normal" },
    { key: "icelandic", tag: "normal" },
    { key: "indian", tag: "normal" },
    { key: "indigenous", tag: "normal" },
    { key: "indonesian", tag: "normal" },
    { key: "iranian", tag: "normal" },
    { key: "iraqi", tag: "normal" },
    { key: "irish", tag: "normal" },
    { key: "israeli", tag: "normal" },
    { key: "italian", tag: "normal" },
    { key: "japanese", tag: "normal" },
    { key: "jewish", tag: "normal" },
    { key: "kazakh", tag: "normal" },
    { key: "kenyan", tag: "normal" },
    { key: "khoi", tag: "normal" },
    { key: "korean", tag: "normal" },
    { key: "latina", tag: "normal" },
    { key: "lebanese", tag: "normal" },
    { key: "maghrebi", tag: "normal" },
    { key: "malaysian", tag: "normal" },
    { key: "maldivian", tag: "normal" },
    { key: "malian", tag: "normal" },
    { key: "masai", tag: "normal" },
    { key: "mexican", tag: "normal" },
    { key: "middle eastern", tag: "normal" },
    { key: "mongolian", tag: "normal" },
    { key: "moroccan", tag: "normal" },
    { key: "mozambican", tag: "normal" },
    { key: "native american", tag: "normal" },
    { key: "new zealand", tag: "normal" },
    { key: "nicaraguan", tag: "normal" },
    { key: "nigerian", tag: "normal" },
    { key: "north african", tag: "normal" },
    { key: "norwegian", tag: "normal" },
    { key: "pakistani", tag: "normal" },
    { key: "panamanian", tag: "normal" },
    { key: "papuan", tag: "normal" },
    { key: "paraguayan", tag: "normal" },
    { key: "persian", tag: "normal" },
    { key: "peruvian", tag: "normal" },
    { key: "polish", tag: "normal" },
    { key: "polynesian", tag: "normal" },
    { key: "portuguese", tag: "normal" },
    { key: "romanian", tag: "normal" },
    { key: "russian", tag: "normal" },
    { key: "scandinavian", tag: "normal" },
    { key: "senegalese", tag: "normal" },
    { key: "serbian", tag: "normal" },
    { key: "singaporean", tag: "normal" },
    { key: "sinhalese", tag: "normal" },
    { key: "slovenian", tag: "normal" },
    { key: "somali", tag: "normal" },
    { key: "south african", tag: "normal" },
    { key: "spanish", tag: "normal" },
    { key: "swedish", tag: "normal" },
    { key: "swiss", tag: "normal" },
    { key: "syrian", tag: "normal" },
    { key: "taiwanese", tag: "normal" },
    { key: "tamil", tag: "normal" },
    { key: "tanzanian", tag: "normal" },
    { key: "thai", tag: "normal" },
    { key: "tunisian", tag: "normal" },
    { key: "turkish", tag: "normal" },
    { key: "ukrainian", tag: "normal" },
    { key: "venezuelan", tag: "normal" },
    { key: "vietnamese", tag: "normal" },
    { key: "zambian", tag: "normal" },
    { key: "zulu", tag: "normal" },
  ],
  Time: [
    { key: "sunrise", tag: "normal" },
    { key: "morning", tag: "normal" },
    { key: "daytime", tag: "normal" },
    { key: "evening", tag: "normal" },
    { key: "sunset", tag: "normal" },
    { key: "night", tag: "normal" },
  ],
  Weather: [
    { key: "rain", tag: "normal" },
    { key: "snowfall", tag: "normal" },
    { key: "snow", tag: "normal" },
    { key: "fog", tag: "normal" },
    { key: "thunderstorm", tag: "normal" },
    { key: "cloud", tag: "normal" },
    { key: "dust storms", tag: "normal" },
    { key: "tornado", tag: "normal" },
    { key: "northern lights", tag: "normal" },
    { key: "darkness", tag: "normal" },
    { key: "solar eclipse", tag: "normal" },
    { key: "lunar eclipse", tag: "normal" },
    { key: "windy", tag: "normal" },
  ],
  Places: [
    { key: "abandoned building", tag: "normal" },
    { key: "airport", tag: "normal" },
    { key: "airplane", tag: "normal" },
    { key: "airship", tag: "normal" },
    { key: "alien planet", tag: "normal" },
    { key: "balcony", tag: "normal" },
    { key: "bamboo forest", tag: "normal" },
    { key: "bar", tag: "normal" },
    { key: "baseball field", tag: "normal" },
    { key: "basement", tag: "normal" },
    { key: "bathroom", tag: "normal" },
    { key: "beach", tag: "normal" },
    { key: "beach bungalow", tag: "normal" },
    { key: "bed", tag: "normal" },
    { key: "bedroom", tag: "normal" },
    { key: "bridge", tag: "normal" },
    { key: "bicycle", tag: "normal" },
    { key: "bus", tag: "normal" },
    { key: "bus station", tag: "normal" },
    { key: "campfire", tag: "normal" },
    { key: "car", tag: "normal" },
    { key: "carnaval", tag: "normal" },
    { key: "castle", tag: "normal" },
    { key: "catacombs", tag: "normal" },
    { key: "cave", tag: "normal" },
    { key: "changing room", tag: "normal" },
    { key: "church", tag: "normal" },
    { key: "classroom", tag: "normal" },
    { key: "club", tag: "normal" },
    { key: "cosplay", tag: "normal" },
    { key: "couch", tag: "normal" },
    { key: "desert", tag: "normal" },
    { key: "docks", tag: "normal" },
    { key: "drive-in cinema", tag: "normal" },
    { key: "dungeon", tag: "normal" },
    { key: "elevator", tag: "normal" },
    { key: "fashion show", tag: "normal" },
    { key: "farmers market", tag: "normal" },
    { key: "football field", tag: "normal" },
    { key: "forest", tag: "normal" },
    { key: "floor", tag: "normal" },
    { key: "garage", tag: "normal" },
    { key: "gas station", tag: "normal" },
    { key: "grocery store", tag: "normal" },
    { key: "gym", tag: "normal" },
    { key: "hot air balloon", tag: "normal" },
    { key: "hot tub", tag: "normal" },
    { key: "house garden", tag: "normal" },
    { key: "industry factory", tag: "normal" },
    { key: "indoors", tag: "normal" },
    { key: "jungle", tag: "normal" },
    { key: "kaaba", tag: "normal" },
    { key: "kitchen", tag: "normal" },
    { key: "laboratory", tag: "normal" },
    { key: "lake", tag: "normal" },
    { key: "lecture hall", tag: "normal" },
    { key: "locker room", tag: "normal" },
    { key: "metro", tag: "normal" },
    { key: "metro station", tag: "normal" },
    { key: "moon", tag: "normal" },
    { key: "mosque", tag: "normal" },
    { key: "motorcycle", tag: "normal" },
    { key: "mountains", tag: "normal" },
    { key: "night club", tag: "normal" },
    { key: "nuclear vault", tag: "normal" },
    { key: "office", tag: "normal" },
    { key: "onsen", tag: "normal" },
    { key: "park", tag: "normal" },
    { key: "parking", tag: "normal" },
    { key: "parlament", tag: "normal" },
    { key: "photo studio", tag: "normal" },
    { key: "pool", tag: "normal" },
    { key: "public", tag: "normal" },
    { key: "public library", tag: "normal" },
    { key: "red carpet", tag: "normal" },
    { key: "restaurant", tag: "normal" },
    { key: "river", tag: "normal" },
    { key: "road", tag: "normal" },
    { key: "rooftop", tag: "normal" },
    { key: "sauna", tag: "normal" },
    { key: "sea", tag: "normal" },
    { key: "shop", tag: "normal" },
    { key: "shopping mall", tag: "normal" },
    { key: "shower", tag: "normal" },
    { key: "sofa", tag: "normal" },
    { key: "space station", tag: "normal" },
    { key: "stadium", tag: "normal" },
    { key: "stairs", tag: "normal" },
    { key: "street", tag: "normal" },
    { key: "strip club", tag: "normal" },
    { key: "tent", tag: "normal" },
    { key: "terrace", tag: "normal" },
    { key: "toilet", tag: "normal" },
    { key: "train", tag: "normal" },
    { key: "train station", tag: "normal" },
    { key: "tunnel", tag: "normal" },
    { key: "underwater", tag: "normal" },
    { key: "volcan", tag: "normal" },
    { key: "waterfall", tag: "normal" },
    { key: "white house", tag: "normal" },
    { key: "yacht", tag: "normal" },
  ],
  "Famous places": [
    { key: "Eiffel Tower, Paris", tag: "normal" },
    { key: "The Colosseum, Rome", tag: "normal" },
    { key: "Statue of Liberty, New York City", tag: "normal" },
    { key: "Yellowstone National Park, USA", tag: "normal" },
    { key: "Machu Picchu, Peru", tag: "normal" },
    { key: "The Acropolis, Athens", tag: "normal" },
    { key: "The Taj Mahal, India", tag: "normal" },
    { key: "Red Light District, Amsterdam", tag: "fetish" },
    { key: "Pyramids of Giza, Egypt", tag: "normal" },
    { key: "Great Wall of China", tag: "normal" },
    { key: "Angkor Wat, Cambodia", tag: "normal" },
    { key: "Petra, Jordan", tag: "normal" },
    { key: "Grand Canyon, USA", tag: "normal" },
    { key: "Stonehenge, England", tag: "normal" },
    { key: "Borobudur, Indonesia", tag: "normal" },
    { key: "Niagara Falls, Canada", tag: "normal" },
    { key: "Bagan, Myanmar", tag: "normal" },
    { key: "Sydney Opera House", tag: "normal" },
    { key: "Mount Kilimanjaro", tag: "normal" },
    { key: "The Louvre, Paris", tag: "normal" },
    { key: "Forbidden City, China", tag: "normal" },
    { key: "Prague Castle, Czech Republic", tag: "normal" },
    { key: "Chichen Itza, Mexico", tag: "normal" },
    { key: "Corcovado and Cristo Redentor, Rio de Janeiro", tag: "normal" },
    { key: "Château de Versailles, France", tag: "normal" },
    { key: "Mount Fuji", tag: "normal" },
    { key: "Central Park, New York City", tag: "normal" },
    { key: "Mesa Verde, USA", tag: "normal" },
    { key: "Terracotta Army, China", tag: "normal" },
    { key: "Mayan Ruins of Tikal, Guatemala", tag: "normal" },
    { key: "Leshan Giant Buddha, China", tag: "normal" },
    { key: "Easter Island", tag: "normal" },
    { key: "Cappadocia", tag: "normal" },
    { key: "Kremlin, Moscow", tag: "normal" },
    { key: "Samarkand, Uzbekistan", tag: "normal" },
    { key: "Kathmandu, Nepal", tag: "normal" },
    { key: "Santorini, Greece", tag: "normal" },
    { key: "Venice, Italy", tag: "normal" },
    { key: "Basílica de la Sagrada Família, Spain", tag: "normal" },
    { key: "Jerusalem, Israel", tag: "normal" },
    { key: "Harajuku, Tokyo", tag: "normal" },
  ],
  Accessories: [
    { key: "belt", tag: "normal" },
    { key: "bow tie", tag: "normal" },
    { key: "tie", tag: "normal" },
    { key: "suspender belt", tag: "fetish" },
    { key: "bows", tag: "normal" },
    { key: "dildo", tag: "porn" },
    { key: "ball gag", tag: "fetish" },
    { key: "toys", tag: "normal" },
    { key: "bottle", tag: "normal" },
    { key: "banana", tag: "fetish" },
    { key: "blindfold", tag: "fetish" },
    { key: "glasses", tag: "normal" },
    { key: "sunglasses", tag: "normal" },
    { key: "face mask", tag: "normal" },
    { key: "gas mask", tag: "porn" },
    { key: "venetian mask", tag: "normal" },
    { key: "plague doctor mask", tag: "normal" },
    { key: "choker", tag: "fetish" },
    { key: "collar", tag: "fetish" },
    { key: "necklace", tag: "normal" },
    { key: "gloves", tag: "normal" },
    { key: "bracelet", tag: "normal" },
    { key: "anklet", tag: "normal" },
    { key: "jewelry", tag: "normal" },
    { key: "earrings", tag: "normal" },
    { key: "hairclip", tag: "normal" },
    { key: "hogtie", tag: "fetish" },
    { key: "rope", tag: "fetish" },
    { key: "cuffs", tag: "fetish" },
    { key: "hat", tag: "normal" },
    { key: "fedora hat", tag: "normal" },
    { key: "posh hat", tag: "normal" },
    { key: "panama hat", tag: "normal" },
    { key: "wizard hat", tag: "normal" },
    { key: "scarf", tag: "normal" },
    { key: "hairband", tag: "normal" },
    { key: "headphones", tag: "normal" },
    { key: "candlelight", tag: "normal" },
    { key: "bunny tail", tag: "fetish" },
    { key: "cat tail", tag: "fetish" },
    { key: "demon tail", tag: "fetish" },
    { key: "dog tail", tag: "fetish" },
    { key: "bunny ears", tag: "sexy" },
    { key: "cat ears", tag: "sexy" },
    { key: "dog ears", tag: "fetish" },
    { key: "cow horns", tag: "fetish" },
    { key: "deer horns", tag: "fetish" },
    { key: "demon horns", tag: "fetish" },
    { key: "demon wings", tag: "fetish" },
    { key: "insect wings", tag: "fetish" },
    { key: "plant wings", tag: "fetish" },
    { key: "bird wings", tag: "fetish" },
    { key: "mechanical wings", tag: "fetish" },
  ],
  Head: [
    { key: "hijab", tag: "normal" },
    { key: "niqab", tag: "normal" },
  ],
  Body: [
    { key: "perfect body", tag: "sexy" },
    { key: "babe", tag: "sexy" },
    { key: "skinny", tag: "normal" },
    { key: "thick", tag: "normal" },
    { key: "chubby", tag: "normal" },
    //{ key: "fat", tag: "normal" },
    //{ key: "bbw", tag: "porn" },
    //{ key: "ssbbw", tag: "porn" },
    { key: "muscular", tag: "normal" },
    { key: "pregnant", tag: "normal" },
    { key: "collarbone", tag: "normal" },
    { key: "bare shoulders", tag: "sexy" },
    { key: "short", tag: "normal" },
    { key: "tall", tag: "normal" },
    { key: "hairy", tag: "normal" },
    { key: "shiny skin", tag: "sexy" },
    { key: "tanned skin", tag: "sexy" },
    { key: "fairer skin", tag: "normal" },
    { key: "oiled body", tag: "sexy" },
    { key: "wet", tag: "sexy" },
    { key: "body soap", tag: "normal" },
    { key: "tan lines", tag: "sexy" },
    { key: "sweat", tag: "normal" },
    { key: "athlete", tag: "normal" },
    { key: "flexible", tag: "normal" },
    { key: "bodybuilder", tag: "normal" },
  ],
  Breasts: [
    { key: "perfect boobs", tag: "porn" },
    { key: "huge boobs", tag: "porn" },
    { key: "big tits", tag: "porn" },
    { key: "small tits", tag: "porn" },
    { key: "saggy tits", tag: "porn" },
    { key: "gigantic boobs", tag: "porn" },
    { key: "natural tits", tag: "porn" },
    { key: "nipples", tag: "porn" },
    { key: "busty", tag: "sexy" },
  ],

  Ass: [
    { key: "big ass", tag: "porn" },
    { key: "small ass", tag: "porn" },
    { key: "big hips", tag: "porn" },
    { key: "pawg", tag: "fetish" },
  ],
  Genitalia: [
    //{"key": "big cock", "tag": "porn"},
    //{"key": "uncircumcised cock", "tag": "porn"},
    //{"key": "big balls", "tag": "porn"},
    //{"key": "veiny dick", "tag": "porn"},
    { key: "shaved", tag: "porn" },
    { key: "pussy juice", tag: "porn" },
    { key: "futanari", tag: "porn" },
  ],
  "Upper Body": [
    { key: "blouse", tag: "normal" },
    { key: "shirt", tag: "normal" },
    { key: "tank top", tag: "sexy" },
    { key: "bra", tag: "sexy" },
    { key: "corset", tag: "sexy" },
    { key: "sweater", tag: "normal" },
    { key: "jacket", tag: "normal" },
    { key: "hoody", tag: "normal" },
    { key: "open shirt", tag: "sexy" },
    { key: "bodysuit", tag: "normal" },
    { key: "sports bra", tag: "sexy" },
    { key: "apron", tag: "normal" },
    { key: "chemise", tag: "normal" },
    { key: "cupless bra", tag: "sexy" },
    { key: "push-up bra", tag: "sexy" },
  ],
  "Lower Body": [
    { key: "trousers", tag: "normal" },
    { key: "jeans", tag: "normal" },
    { key: "short shorts", tag: "sexy" },
    { key: "micro skirt", tag: "sexy" },
    { key: "mini skirt", tag: "sexy" },
    { key: "long skirt", tag: "normal" },
    { key: "panties", tag: "sexy" },
    { key: "thong", tag: "fetish" },
    { key: "yoga pants", tag: "sexy" },
  ],
  "Full Body": [
    { key: "dress", tag: "normal" },
    { key: "jumpsuit", tag: "normal" },
    { key: "onesie", tag: "normal" },
    { key: "bikini", tag: "sexy" },
    { key: "one piece swimsuit", tag: "sexy" },
    { key: "lingerie", tag: "sexy" },
    { key: "nightgown", tag: "normal" },
    { key: "pajamas", tag: "normal" },
    { key: "toga", tag: "normal" },
    { key: "tunic", tag: "normal" },
    { key: "sari", tag: "normal" },
    { key: "salwar", tag: "normal" },
    { key: "sundress", tag: "normal" },
    { key: "cheongsam", tag: "normal" },
    { key: "dirndl", tag: "normal" },
    { key: "leotard", tag: "normal" },
    { key: "negligee", tag: "sexy" },
    { key: "bathrobe", tag: "normal" },
  ],
  Legs: [
    { key: "stockings", tag: "sexy" },
    { key: "pantyhose", tag: "sexy" },
    { key: "leggings", tag: "normal" },
    { key: "thigh socks", tag: "sexy" },
    { key: "high socks", tag: "sexy" },
    { key: "fishnet", tag: "sexy" },
  ],
  Feet: [
    { key: "boots", tag: "normal" },
    { key: "high heels", tag: "sexy" },
    { key: "strappy heels", tag: "sexy" },
  ],
  "Special/Themed": [
    { key: "tattoos", tag: "normal" },
    { key: "piercing", tag: "normal" },
    { key: "selfie", tag: "normal" },
    { key: "mirror selfie", tag: "normal" },
    { key: "armpits", tag: "fetish" },
    { key: "saliva", tag: "fetish" },
    { key: "bimbo", tag: "fetish" },
    { key: "slutty", tag: "porn" },
    { key: "amateur", tag: "porn" },
    { key: "gyaru", tag: "fetish" },
    { key: "cosplay", tag: "sexy" },
    { key: "fantasy armor", tag: "fetish" },
    { key: "steampunk", tag: "normal" },
    { key: "medieval", tag: "normal" },
    { key: "victorian", tag: "normal" },
    { key: "traditional", tag: "normal" },
    { key: "tribal", tag: "normal" },
    { key: "wedding", tag: "normal" },
    { key: "bdsm", tag: "fetish" },
    { key: "fetish", tag: "fetish" },
    { key: "boudoir", tag: "fetish" },
    { key: "angel", tag: "fetish" },
    { key: "sailor", tag: "normal" },
    { key: "lumberjack", tag: "normal" },
    { key: "roman", tag: "normal" },
    { key: "coronation robes", tag: "normal" },
    { key: "vyshyvanka", tag: "normal" },
    { key: "40s", tag: "normal" },
    { key: "50s", tag: "normal" },
    { key: "60s", tag: "normal" },
    { key: "70s", tag: "normal" },
    { key: "80s", tag: "normal" },
    { key: "90s", tag: "normal" },
    { key: "halloween", tag: "normal" },
  ],
  "Clothing Style": [
    { key: "nude", tag: "porn" },
    { key: "topless", tag: "porn" },
    { key: "bottomless", tag: "porn" },
    { key: "partially nude", tag: "porn" },
    { key: "fully clothed", tag: "normal" },
    { key: "transparent", tag: "sexy" },
    { key: "casual", tag: "normal" },
    { key: "stylish", tag: "normal" },
    { key: "tight", tag: "normal" },
    { key: "oversized shirt", tag: "normal" },
    { key: "mesh", tag: "fetish" },
    { key: "bodypaint", tag: "sexy" },
  ],
  Sports: [
    { key: "basketball", tag: "normal" },
    { key: "beach volleyball", tag: "normal" },
    { key: "golf", tag: "normal" },
    { key: "soccer", tag: "normal" },
    { key: "sports", tag: "normal" },
    { key: "tennis", tag: "normal" },
  ],
  "Clothes material": [
    { key: "latex", tag: "sexy" },
    { key: "nylon", tag: "normal" },
    { key: "fur", tag: "normal" },
    { key: "denim", tag: "normal" },
    { key: "silk", tag: "normal" },
    { key: "cotton", tag: "normal" },
    { key: "leather", tag: "fetish" },
    { key: "corduroy", tag: "normal" },
    { key: "velveteen", tag: "normal" },
    { key: "spandex", tag: "normal" },
    { key: "lycra", tag: "normal" },
    { key: "knitted", tag: "normal" },
    { key: "fish scales", tag: "fetish" },
    { key: "dragon scales", tag: "fetish" },
    { key: "carbon fiber", tag: "normal" },
    { key: "glass", tag: "normal" },
    { key: "crystal", tag: "normal" },
    { key: "diamond", tag: "normal" },
    { key: "emerald", tag: "normal" },
    { key: "ruby", tag: "normal" },
    { key: "sapphire", tag: "normal" },
    { key: "marble", tag: "normal" },
    { key: "pearl", tag: "normal" },
    { key: "flowers", tag: "normal" },
    { key: "paper", tag: "normal" },
    { key: "plastic", tag: "normal" },
    { key: "wood", tag: "normal" },
    { key: "metal", tag: "normal" },
    { key: "gold", tag: "normal" },
    { key: "platinum", tag: "normal" },
    { key: "silver", tag: "normal" },
    { key: "copper", tag: "normal" },
    { key: "bronze", tag: "normal" },
    { key: "patina", tag: "normal" },
    { key: "titanium", tag: "normal" },
    { key: "chrome", tag: "normal" },
    { key: "aluminum", tag: "normal" },
    { key: "chainmail", tag: "fetish" },
    { key: "anodized metal", tag: "normal" },
    { key: "damascus steel", tag: "normal" },
  ],
  Character: [
    { key: "beauty", tag: "normal" },
    { key: "blonde", tag: "normal" },
    { key: "slut girl", tag: "sexy" },
    //{ key: "vixen", tag: "sexy" },
    { key: "hottie", tag: "sexy" },
    { key: "chick", tag: "sexy" },
    { key: "sexy chick", tag: "sexy" },
    { key: "bombshell girl", tag: "sexy" },
    { key: "nymph girl", tag: "fetish" },
    { key: "minx girl", tag: "sexy" },
    { key: "bimbo girl", tag: "sexy" },
    //{ key: "floozy", tag: "sexy" },
    { key: "temptress", tag: "sexy" },
    { key: "seductress", tag: "sexy" },
    //{ key: "tease", tag: "sexy" },
    { key: "tigress", tag: "sexy" },
    //{ key: "harlot", tag: "sexy" },
    //{ key: "nympho", tag: "fetish" },
    //{ key: "cougar", tag: "normal" },
    { key: "mistress", tag: "fetish" },
    //{ key: "dominatrix", tag: "fetish" },
    { key: "pin-up", tag: "sexy" },
    { key: "goddess", tag: "fetish" },
    //{ key: "kitten girl", tag: "fetish" },
  ],
  Role: [
    { key: "athlete", tag: "normal" },
    { key: "barista", tag: "normal" },
    { key: "belly dancer", tag: "sexy" },
    { key: "cheerleader", tag: "sexy" },
    //{ key: "clown", tag: "normal" },
    //{ key: "construction worker", tag: "normal" },
    //{ key: "cyborg", tag: "normal" },
    { key: "devil", tag: "fetish" },
    { key: "doctor", tag: "normal" },
    { key: "dominatrix", tag: "fetish" },
    { key: "elf", tag: "normal" },
    { key: "emo", tag: "normal" },
    { key: "fairy", tag: "normal" },
    //{ key: "firefighter", tag: "normal" },
    //{ key: "flight attendant", tag: "normal" },
    { key: "geisha", tag: "normal" },
    //{ key: "goblin", tag: "normal" },
    { key: "goth", tag: "normal" },
    { key: "gymnast", tag: "normal" },
    { key: "harlequin", tag: "normal" },
    { key: "maid", tag: "sexy" },
    { key: "mariachi", tag: "normal" },
    { key: "mermaid", tag: "normal" },
    //{ key: "military", tag: "normal" },
    { key: "ninja", tag: "normal" },
    //{ key: "nun", tag: "fetish" },
    { key: "nurse", tag: "sexy" },
    //{ key: "pilot", tag: "normal" },
    { key: "pirate", tag: "normal" },
    { key: "police", tag: "normal" },
    { key: "princess", tag: "normal" },
    { key: "prisoner", tag: "normal" },
    //{ key: "professor", tag: "normal" },
    //{ key: "race driver", tag: "normal" },
    //{ key: "robot", tag: "normal" },
    { key: "santa", tag: "normal" },
    { key: "secretary", tag: "sexy" },
    { key: "siren", tag: "sexy" },
    { key: "sorority girl", tag: "fetish" },
    { key: "stripper", tag: "sexy" },
   // { key: "superhero", tag: "normal" },
    { key: "teacher", tag: "sexy" },
    { key: "vampire", tag: "fetish" },
    { key: "viking", tag: "normal" },
    { key: "waitress", tag: "normal" },
    //{ key: "welder", tag: "normal" },
    { key: "wife", tag: "normal" },
    { key: "witch", tag: "normal" },
  ],
};

function generateSexyPrompt(style = null) {
  const singleRoleTemplates = [
    "{View} of {Age} {Ethnicity}, {Hair Color} {Hair Style}, {Face} expression, {Body}, {Breasts}, {Clothes material} {Upper Body}, {Lower Body}, {Tags}, {Action} in {Places} during {Time} with {Weather}",
    "{Age} {Ethnicity} {Character} {Role}, {Style} {Clothes material} {Full Body}, {Body}, {Breasts}, {Tags}, {View}, {Face} expression, {Action} at {Time} in {Places}",
    "{Character} {Role}, {Hair Color} {Hair Style}, {Body}, {Breasts}, {Colors} outfit, {Tags}, {Action} near {Famous places} during {Weather}",
    "{Ethnicity} {Character} {Role}, {Clothes material} {Upper Body}, {Body}, {Breasts}, {Tags}, {Action} with {Accessories} at {Time} in {Places}",
    "{Age} {Character} {Role}, {Hair Color} hair, {Face} expression, {Body}, {Breasts}, {Style} {Lower Body}, {Tags}, {Action} near {Famous places}",
    "{View} of {Ethnicity} {Character} {Role}, {Hair Style}, {Body}, {Breasts}, {Colors} {Full Body}, {Tags}, {Action} in {Weather} at {Places}",
    "{Age} {Character} {Role}, {Hair Color} hair, {Body}, {Breasts}, {Clothes material} {Upper Body}, {Tags}, {Action} during {Time} at {Famous places}",
    "{Ethnicity} {Character} {Role}, {Hair Style}, {Body}, {Breasts}, {Accessories}, {Tags}, {Action} in {Places} with {Weather} backdrop",
    "{Character} {Role}, {Colors} {Lower Body}, {Body}, {Breasts}, {Tags}, {Face} expression, {Action} near {Famous places} at {Time}",
    "{View} of {Age} {Ethnicity} {Character} {Role}, {Hair Color} hair, {Body}, {Breasts}, {Style} {Full Body}, {Tags}, {Action} during {Weather} in {Places}",
    "{Character} {Role}, {Hair Color} {Hair Style}, {Face} expression, {Body}, {Breasts}, {Upper Body}, {Lower Body}, {Clothes material}, {Tags}, {Action} in {Places} during {Time} with {Weather}",
    "{Age} {Ethnicity} {Character} {Role}, {Style} {Full Body}, {Clothes material}, {Body}, {Breasts}, {Tags}, {Action} in {Places} at {Time} with {Weather}",
    "{Character} {Role}, {Hair Color} {Hair Style}, {Face} expression, {Body}, {Breasts}, {Colors} {Upper Body}, {Lower Body}, {Tags}, {Action} near {Famous places} at {Time}",
    "{Ethnicity} {Character} {Role}, {Body}, {Breasts}, {Tags}, {Upper Body}, {Lower Body}, {Clothes material}, {Action} in {Places} during {Time} with {Weather}",
    "{Age} {Character} {Role}, {Hair Color} {Hair Style}, {Face} expression, {Body}, {Breasts}, {Style} {Full Body}, {Tags}, {Action} near {Famous places} with {Weather}",
    "{View} of {Ethnicity} {Character} {Role}, {Hair Style}, {Body}, {Breasts}, {Colors} {Upper Body}, {Lower Body}, {Tags}, {Action} in {Places} during {Time} with {Weather}",
    "{Age} {Character} {Role}, {Hair Color} {Hair Style}, {Body}, {Breasts}, {Clothes material} {Upper Body}, {Lower Body}, {Tags}, {Action} at {Famous places} during {Time} with {Weather}",
    "{Ethnicity} {Character} {Role}, {Hair Style}, {Body}, {Breasts}, {Accessories}, {Tags}, {Action} in {Places} with {Weather} at {Time}",
    "{Character} {Role}, {Colors} {Upper Body}, {Lower Body}, {Body}, {Breasts}, {Tags}, {Face} expression, {Action} near {Famous places} at {Time}",
    "{View} of {Age} {Ethnicity} {Character} {Role}, {Hair Color} {Hair Style}, {Body}, {Breasts}, {Style} {Full Body}, {Tags}, {Action} in {Places} during {Time} with {Weather}",
    "{Character} {Role}, {Hair Color} {Hair Style}, {Body}, {Breasts}, {Upper Body}, {Lower Body}, {Colors}, {Tags}, {Action} in {Places} during {Time} with {Weather}",
    "{Age} {Ethnicity} {Character} {Role}, {Clothes material} {Full Body}, {Body}, {Breasts}, {Tags}, {Action} at {Famous places} during {Weather}",
    "{Character} {Role}, {Hair Color} {Hair Style}, {Face} expression, {Body}, {Breasts}, {Colors} {Upper Body}, {Lower Body}, {Tags}, {Action} near {Famous places} at {Time}",
    "{Ethnicity} {Character} {Role}, {Body}, {Breasts}, {Tags}, {Upper Body}, {Lower Body}, {Clothes material}, {Action} in {Places} during {Time} with {Weather}",
    "{Age} {Character} {Role}, {Hair Color} {Hair Style}, {Face} expression, {Body}, {Breasts}, {Style} {Full Body}, {Tags}, {Action} near {Famous places} with {Weather}",
    "{View} of {Ethnicity} {Character} {Role}, {Hair Style}, {Body}, {Breasts}, {Colors} {Upper Body}, {Lower Body}, {Tags}, {Action} in {Places} during {Time} with {Weather}",
    "{Age} {Character} {Role}, {Hair Color} {Hair Style}, {Body}, {Breasts}, {Clothes material} {Upper Body}, {Lower Body}, {Tags}, {Action} at {Famous places} during {Time} with {Weather}",
    "{Ethnicity} {Character} {Role}, {Hair Style}, {Body}, {Breasts}, {Accessories}, {Tags}, {Action} in {Places} with {Weather} at {Time}",
    "{Character} {Role}, {Colors} {Upper Body}, {Lower Body}, {Body}, {Breasts}, {Tags}, {Face} expression, {Action} near {Famous places} at {Time}",
    "{View} of {Age} {Ethnicity} {Character} {Role}, {Hair Color} {Hair Style}, {Body}, {Breasts}, {Style} {Full Body}, {Tags}, {Action} in {Places} during {Time} with {Weather}",
];

  const doubleRoleTemplates = [
    "{Age1} {Ethnicity1} {Character} {Role1}, {Hair Color1} {Hair Style1}, {Clothes material1} {Upper Body1}, {Body1}, {Breasts1}, {Tags1}, {Action} with {Age2} {Ethnicity2} {Character} {Role2}, {Clothes material2} {Lower Body2}, {Body2}, {Breasts2}, {Tags2}, in {Places} during {Time}",
    "{Character} {Role1}, {Hair Style1}, {Body1}, {Breasts1}, {Tags1}, and {Character} {Role2}, {Hair Color2} hair, {Body2}, {Breasts2}, {Tags2}, both in {Style} {Full Body}, {Action} at {Famous places} during {Weather}",
    "{Ethnicity1} {Character} {Role1}, {Colors1} {Upper Body1}, {Body1}, {Breasts1}, {Tags1}, {Action} with {Ethnicity2} {Character} {Role2}, {Colors2} {Lower Body2}, {Body2}, {Breasts2}, {Tags2}, both with {Face} expressions in {Places}",
    "{Age1} {Character} {Role1}, {Hair Color1} hair, {Body1}, {Breasts1}, {Tags1}, and {Age2} {Character} {Role2}, {Hair Style2}, {Body2}, {Breasts2}, {Tags2}, both wearing {Accessories}, {Action} in {Weather} at {Time}",
    "{View} of {Character} {Role1}, {Clothes material1} {Full Body1}, {Body1}, {Breasts1}, {Tags1}, {Action} with {Character} {Role2}, {Style} {Upper Body2}, {Body2}, {Breasts2}, {Tags2}, at {Famous places} during {Time}",
    "{Age1} {Ethnicity1} {Character} {Role1}, {Upper Body1} of {Clothes material1}, {Body1}, {Breasts1}, {Tags1}, {Action} with {Age2} {Ethnicity2} {Character} {Role2}, {Lower Body2} of {Clothes material2}, {Body2}, {Breasts2}, {Tags2}, in {Places} at {Time} with {Weather}",
    "{Character} {Role1}, {Hair Style1}, {Face} expression, {Body1}, {Breasts1}, {Tags1}, and {Character} {Role2}, {Hair Color2} {Hair Style2}, {Body2}, {Breasts2}, {Tags2}, both in {Style} {Full Body}, {Action} at {Famous places} during {Weather}",
    "{Ethnicity1} {Character} {Role1}, {Colors1} {Upper Body1}, {Body1}, {Breasts1}, {Tags1}, {Action} with {Ethnicity2} {Character} {Role2}, {Colors2} {Lower Body2}, {Body2}, {Breasts2}, {Tags2}, both with {Face} expressions in {Places} during {Time} with {Weather}",
    "{Age1} {Character} {Role1}, {Hair Color1} {Hair Style1}, {Body1}, {Breasts1}, {Tags1}, and {Age2} {Character} {Role2}, {Hair Style2}, {Body2}, {Breasts2}, {Tags2}, both with {Accessories}, {Action} in {Weather} at {Famous places} at {Time}",
    "{View} of {Character} {Role1}, {Clothes material1} {Upper Body1}, {Body1}, {Breasts1}, {Tags1}, {Action} with {Character} {Role2}, {Style} {Lower Body2}, {Body2}, {Breasts2}, {Tags2}, at {Places} during {Time} with {Weather}",
    "{Age1} {Ethnicity1} {Character} {Role1}, {Upper Body1} of {Clothes material1}, {Body1}, {Breasts1}, {Tags1}, {Action} with {Age2} {Ethnicity2} {Character} {Role2}, {Lower Body2} of {Clothes material2}, {Body2}, {Breasts2}, {Tags2}, in {Places} at {Time} with {Weather}",
    "{Character} {Role1}, {Hair Style1}, {Face} expression, {Body1}, {Breasts1}, {Tags1}, and {Character} {Role2}, {Hair Color2} {Hair Style2}, {Body2}, {Breasts2}, {Tags2}, both in {Style} {Full Body}, {Action} at {Famous places} during {Weather}",
    "{Ethnicity1} {Character} {Role1}, {Colors1} {Upper Body1}, {Body1}, {Breasts1}, {Tags1}, {Action} with {Ethnicity2} {Character} {Role2}, {Colors2} {Lower Body2}, {Body2}, {Breasts2}, {Tags2}, both with {Face} expressions in {Places} during {Time} with {Weather}",
    "{Age1} {Character} {Role1}, {Hair Color1} hair, {Body1}, {Breasts1}, {Tags1}, and {Age2} {Character} {Role2}, {Hair Style2}, {Body2}, {Breasts2}, {Tags2}, both wearing {Accessories}, {Action} in {Weather} at {Time}",
    "{Age1} {Ethnicity1} {Character} {Role1}, {Upper Body1} of {Clothes material1}, {Body1}, {Breasts1}, {Tags1}, {Action} with {Age2} {Ethnicity2} {Character} {Role2}, {Lower Body2} of {Clothes material2}, {Body2}, {Breasts2}, {Tags2}, in {Places} at {Time} with {Weather}",
    "{Character} {Role1}, {Hair Style1}, {Face} expression, {Body1}, {Breasts1}, {Tags1}, and {Character} {Role2}, {Hair Color2} {Hair Style2}, {Body2}, {Breasts2}, {Tags2}, both in {Style} {Full Body}, {Action} at {Famous places} during {Weather}",
    "{Character} {Role1}, {Hair Style1}, {Face} expression, {Body1}, {Breasts1}, {Tags1}, and {Character} {Role2}, {Hair Color2} {Hair Style2}, {Body2}, {Breasts2}, {Tags2}, both wearing {Style} {Full Body}, {Action} at {Famous places} during {Weather}",
    "{Ethnicity1} {Character} {Role1}, {Colors1} {Upper Body1}, {Body1}, {Breasts1}, {Tags1}, {Action} with {Ethnicity2} {Character} {Role2}, {Colors2} {Lower Body2}, {Body2}, {Breasts2}, {Tags2}, both with {Face} expressions in {Places} during {Time} with {Weather}",
];
  const mixedRoleTemplates = [
    "A {Age} {Ethnicity} {Character} {Role} with {Hair Color} {Hair Style} in {Clothes material} {Upper Body}, {Body}, {Breasts}, {Tags}, {Action} with a man in {Places} during {Time}",
    "{Character} {Role} with {Hair Style}, {Body}, {Breasts}, {Tags}, {Action} with a shirtless man, both in {Style} attire at {Famous places} during {Weather}",
    "{Ethnicity} {Character} {Role} in {Colors} {Upper Body}, {Body}, {Breasts}, {Tags}, {Action} with a suited man, both with {Face} expressions in {Places}",
    "{Age} {Character} {Role}, {Hair Color} hair, {Body}, {Breasts}, {Tags}, {Action} with a man in casual wear in {Weather} at {Time}",
    "{View} of {Character} {Role} in {Clothes material} {Full Body}, {Body}, {Breasts}, {Tags}, {Action} with a well-dressed man at {Famous places} during {Time}",
    "{Age} {Ethnicity} {Character} {Role} in {Upper Body} made of {Clothes material}, {Body}, {Breasts}, {Tags}, {Action} with a man in swimming trunks, both in {Places} at {Time} with {Weather}",
    "{Character} {Role} with {Hair Style}, {Face} expression, {Body}, {Breasts}, {Tags}, {Action} with a muscular man, both at {Famous places} during {Weather}",
    "{Ethnicity} {Character} {Role} in {Colors} {Upper Body}, {Body}, {Breasts}, {Tags}, {Action} with a man in a tuxedo in {Places} during {Time} with {Weather}",
    "{Age} {Character} {Role}, {Hair Color} {Hair Style}, {Body}, {Breasts}, {Tags}, {Action} with a man with a camera in {Weather} at {Famous places} at {Time}",
    "{View} of {Character} {Role} in {Clothes material} {Upper Body}, {Body}, {Breasts}, {Tags}, {Action} with a man reading a book, at {Places} during {Time} with {Weather}",
    "{Age} {Ethnicity} {Character} {Role} in {Full Body}, {Body}, {Breasts}, {Tags}, {Action} with a man offering flowers, both in {Places} at {Time} with {Weather}",
    "{Character} {Role} with {Hair Style}, {Face} expression, {Body}, {Breasts}, {Tags}, {Action} with a man in a business suit at an office during {Time}",
    "{Ethnicity} {Character} {Role} in {Colors} bikini, {Body}, {Breasts}, {Tags}, {Action} with a tanned man on the beach during {Weather}",
    "{Age} {Character} {Role}, {Hair Color} hair, {Body}, {Breasts}, {Tags}, {Action} with a man in a designer suit at {Famous places}",
    "{View} of {Character} {Role} in {Clothes material} {Lower Body}, {Body}, {Breasts}, {Tags}, {Action} with a male masseuse at a spa during {Time}",
    "{Age} {Ethnicity} {Character} {Role} in {Upper Body} and shorts, {Body}, {Breasts}, {Tags}, {Action} with a rugged man in hiking gear, both in {Places} at {Time} with {Weather}",
    "{Character} {Role} with {Hair Style}, {Face} expression, {Body}, {Breasts}, {Tags}, {Action} with a male painter in an art studio during {Time}",
    "{Ethnicity} {Character} {Role} in {Colors} sports bra and leggings, {Body}, {Breasts}, {Tags}, {Action} with a male personal trainer in a gym",
    "{Age} {Character} {Role}, {Hair Color} {Hair Style}, {Body}, {Breasts}, {Tags}, {Action} with a man in a tuxedo at a ballroom in {Famous places} at {Time}",
    "{Character} {Role} in {Clothes material} {Full Body}, {Body}, {Breasts}, {Tags}, {Action} with a man in jeans and a t-shirt at {Places} during {Time} with {Weather}",
];
  function getRandomItem(category) {
    let items = data[category];
    if (style) {
      items = items.filter((item) => style.includes(item.tag));
    }
    return items[Math.floor(Math.random() * items.length)]?.key || "";
  }

  function fillTemplate(template) {
    return template.replace(/{([a-zA-Z ]+\d?)}/g, (match, category) => {
      const baseCategory = category.replace(/\d+$/, "");
      if (data[baseCategory]) {
        return getRandomItem(baseCategory);
      }
      return match; // Return unchanged if category not found
    });
  }

  // 30% chance for a double role prompt
  chance = Math.random();
  templates = singleRoleTemplates;
  if (chance <= 0.3) {
    templates = singleRoleTemplates;
  } else if (chance <= 0.6) {
    templates = doubleRoleTemplates;
  } else {
    templates = mixedRoleTemplates;
  }
  const template = templates[Math.floor(Math.random() * templates.length)];
  return fillTemplate(template);
}

// Usage example:
console.log(generateSexyPrompt());
